### ISSUE TITLE
Possible SRID issue on geometries returned from routing?

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/dataservices-api#104]
Hey guys

Andy and myself where having trouble with the returned geometries from the router function. When we tried to view a map with more than one routing geometry nothing would show up. If we tried to create a table form the query it would fail with the standard error you get when table creation fails. 

The only way we could get either to work was to explicitly set the SRID on the returned geometries. Then it seemed to work ok.

This is an exaple query that eventually worked 

```postgresql 
Select 
ST_SetSRID((cdb_route_point_to_point(ST_POINTN(ST_LINEMERGE(the_geom),1),ST_POINTN(ST_LINEMERGE(the_geom),2), 'car')).shape, 4326) as routing from stuartlynn.chicago_bluetooth_routing_segments
where cartodb_id < 10
``` 

on this table : https://team.cartodb.com/u/stuartlynn/tables/chicago_bluetooth_routing_segments/public

would love some advice

**Comment by ethervoid** [comment]
Hum the SRID of the `shape` field should be 4326 always as you can see [here](https://github.com/CartoDB/dataservices-api/blob/master/server/extension/sql/0.5.0/100_routing_helper.sql#L2).

Maybe is by using the `.shape` notation. Could you please us SELECT shape FROM... just to verify?

**Comment by rafatower** [comment]
the SRID should be already set in the returned geometries, shouldn't it, @ethervoid ?

**Comment by ethervoid** [comment]
Yes, I've linked the return type with the SRID
