### ISSUE TITLE
Advice / thoughts about bulk routing and joining with existing columns

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/dataservices-api#105]
Was trying to recreate some of the work that we had been doing with routing on the research team with the internal routing function. It works really well in its current from for routing single trips but it can get tricky if your trying to route multiple rows in a table. The flow is something along the lines of 

Grab a start geometry and end geometry from the row, call cdb_route_point_to_point get back the shape, distance and duration, join these with columns from the original row and return this for each row. 

The best way I can think to do this is like : 
```postgresql
with segments as (
	SELECT * FROM stuartlynn.chicago_bluetooth_routing_segments 
 ),

a as(
 	Select  cdb_route_point_to_point(ST_POINTN(ST_LINEMERGE(the_geom),1),ST_POINTN(ST_LINEMERGE(the_geom),2), 'car') as routing, cartodb_id from segments 
 )

SELECT a.* from segments
join a 
on a.cartodb_id = segments.cartodb_id
```

but thats pretty clunky. Do you have any advice about how we can potentially do more than one route at a time? This is hugely powerful if we can allow people to do it so we might need a wrapper function to 
make it easy for users to bulk route.

Let me know what you think

**Comment by ethervoid** [comment]
The dataservices API works for one row at a time, like the geocoder for example. We have in mind to make a function the lets the user use more than two points like you've pointed here #104 but AFAIK there is no intention to create a bulk function for routing 

// @rafatower

**Comment by rafatower** [comment]
We won't support any kind of bulk operation directly in the routing api. Reasons for that:
- separation of concerns, single responsibility principle
- simplicity
- routing requests are eventually sent one by one to 3rd party routing service
- pl/proxy sends requests to backend server row-by-row
- any bulk operations should go through the sql batch api, that the platform team has developed.

Consider the dataservices API a building block, not some sort of final solution to any problem. As such I do believe it is flexible enough to implement different use cases (and your code snippet is just proof of that).

That said, we may consider a caching layer in the future and if you have a proposal for a different API interface go ahead and we'll consider it. The more specific the better.
