### ISSUE TITLE
Multiwaypoint routing

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/dataservices-api#106]
The new routing functions are awesome but it would be great to do multi waypoint routing. I know that Valhalla supports this pretty easily and returns multiple segments for the routing. I think we could join the resulting geometry for the different segments and just return that but I think being able to describe multiple waypoints would be useful. So a 

```postgresql
cdb_route_with_waypoints(waypoints geom[], method text)
```

Would be awesome to have

**Comment by ethervoid** [comment]
Yes, Valhalla supports it but right now we are going to serve a point to point routing function but we have in mind to make more powerful routing functions

**Comment by iriberri** [comment]
Sneak peek:

![image](https://cloud.githubusercontent.com/assets/1730320/15536053/19acbdca-2270-11e6-9379-b6d64fdc3769.png)
