### ISSUE TITLE
Integrate the Mapzen geocoder service

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/dataservices-api#115]
Add the Mapzen geocoder service to our street level geocoder

**Comment by ethervoid** [comment]
Question:

- How are we gonna configure it for the users? I mean, right now the `geocoder_type` is setted to `here` by default and if the user defines the google config then they have google as their geocoder type.

**Comment by javisantana** [comment]
could we have a mapzen geocoder_type and then use it when we decide to?

**Comment by ethervoid** [comment]
We have it in metadata, if we manually set it to `mapzen` it'll use the mapzen geocoder

**Comment by javisantana** [comment]
ok, that's perfect for now, we will see when we enable it

**Comment by ethervoid** [comment]
Related #119
