### ISSUE TITLE
include brief description of how named places are chosen

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/dataservices-api#123]
Information about how a named place is chosen (most populous city with same name?) would be helpful

cc @csobier

**Comment by iriberri** [comment]
@ohasselblad I understand you mean in the public docs? Or this is more an internal/development docs thing (in which case, perhaps the data-services repo would fit better)?

**Comment by ohasselblad** [comment]
I mean it more as a communicate to user/docs issue.
