### ISSUE TITLE
Isolines monthly quota reset

### ISSUE THREAD

**Issue by yasharora73** [CartoDB/dataservices-api#148]
Hey guys,

We are currently thinking of selling Isolines in yearly packages. The issue I am thinking about is the monthly limits. Lets say we give someone 100k Isolines for the whole year, will the limit refresh every month and the customer will get 100k every month? If that is the case, is it possible to give them 100k and have that limit not refresh every month meaning it goes down depending on their usage and does not refresh at all unless we give them more manually?

If making that change is really complicated, no problem at all. I can discuss within the sales team on how best to go about the monthly refresh thing.

Thanks

**Comment by yasharora73** [comment]
@vhamer

**Comment by ethervoid** [comment]
Is a hard change basically because is not only for isolines, is the whole billing system what is affected by this. So it's very unlikable to change it to yearly by now.
