### ISSUE TITLE
Document integrated Data Observatory functions

### ISSUE THREAD

**Issue by csobier** [CartoDB/dataservices-api#161]
As per the [Docs requirements](https://github.com/CartoDB/docs/issues/788) for the Data Observatory release, add "Demographics" and "Segmentations" as new functions to the Data Services API doc, and document the following:
- [x] OBS_GetDemographicSnapshot( Point Geometry );
- [x] OBS_GetSegmentationSnapshot( Point Geometry );

@ethervoid, I know you are currently writing the code. I created this issue for documentation tracking in this repo.

**Comment by csobier** [comment]
@ethervoid, can you confirm if the code will appear as stated in this issue?

**Comment by ethervoid** [comment]
What do you mean by 'code' , I'm a bit lost hehe :)

**Comment by csobier** [comment]
Meaning, does the function signature need to match?  i.e. `obs_get_demographic_snapshot` to `obs_GetDemographicSnapshot`  Tagging @rafatower and @andrewxhill for confirmation.

**Comment by andrewxhill** [comment]
These ones are dead, 'obs_get_demographic_snapshot'
By the time of release, they will be the form, 'OBS_GetDemographicSnapshot'

**Comment by csobier** [comment]
Final docs PR in review: https://github.com/CartoDB/dataservices-api/pull/165, waiting for sign-off.
