### ISSUE TITLE
Isolines quota for Iggbo

### ISSUE THREAD

**Issue by yasharora73** [CartoDB/dataservices-api#163]
Hey @ethervoid 

We have a user Iggbo asking about how many Isolines credits they have left. We are looking to sell them a package of 100k a month and they are just trying to get an idea of usage before committing. Carla mentioned you could help
https://cartodb.com/superadmin/users/208156

This question will come up more and more. Could you please tell @oriolbx how to check this quota? He can then explain to the rest of the support team. 

Thanks

**Comment by ethervoid** [comment]
That issue should go to management, please open it there

**Comment by ethervoid** [comment]
Issue moved to [CartoDB/cartodb-management #4441](https://github.com/CartoDB/cartodb-management/issues/4441) via [**ZenHub.io**](https://www.zenhub.io/)
