### ISSUE TITLE
Default to NULL for optional args in observatory functions

### ISSUE THREAD

**Issue by talos** [CartoDB/dataservices-api#169]
https://github.com/CartoDB/dataservices-api/edit/master/client/renderer/interface.yaml#L92-L103

`time_span` and `geometry_level` should default to NULL.  In cases where the user does not select one, then we programmatically determine latest time_span & geometry_level.

**Comment by iriberri** [comment]
All the new functions (Client version 0.5.0) have NULL as default, except for the two deprecated `obs_get_demographic_snapshot` and `obs_get_segment_snapshot` which we didn't edit.

**Comment by talos** [comment]
👍 we made this change for our functions, too.
