### ISSUE TITLE
Docs - Broken markdown title in segmentation

### ISSUE THREAD

**Issue by iriberri** [CartoDB/dataservices-api#183]
![image](https://cloud.githubusercontent.com/assets/1730320/15388254/5b95b282-1db1-11e6-87de-eec37b0baaca.png)

https://docs.cartodb.com/cartodb-platform/dataservices-api/segmentation-functions/

The site is showing `### Examples` and not rendering the markdown.

**Comment by csobier** [comment]
Oh, markdown how I ~~~love~~~ you so..
Thanks, I'm on it!
