### ISSUE TITLE
Arbitrary ordering causes failure in OBS Integration Test

### ISSUE THREAD

**Issue by talos** [CartoDB/dataservices-api#207]
Brought up by @rafatower in https://github.com/CartoDB/observatory-extension/issues/113

Here: https://github.com/CartoDB/dataservices-api/blob/b33730aae3b1c2de4917782c014e80de8b189753/test/integration/test_data_observatory_functions.py#L132

The requested `obs_search` will return a row for every obs_column that is for "total_pop", which is not just in Spain but also in the US and UK.  Therefore the test passing depends on whether the Spanish measure "es.ine.t1_1" happens to be the first in the response.  One possible solution would be to narrow the query:

```
SELECT id FROM OBS_Search('total population')
WHERE id LIKE 'es.ine%' LIMIT 1
```

This is likely to consistently work since there should be only one total population measure for INE.  Another approach would be to have no limit, but confirm that "es.ine.t1_1" is somewhere in the results.  Or, a combination of the two strategies could be used, with the above query but no `LIMIT`.

Note that above I changed the search from "total_pop" to "total population".  `OBS_Search` is meant to be a human-readable plain text search mechanism.  While using underscores is not wrong, it's a bit counter to the intentions of the function, and searching for "total_pop" is functionally equivalent to searching for "total pop" (which would more human-ly be "total population").

**Comment by rafatower** [comment]
I don't think the ordering should be part of the API, at least not part of the dataservices-api as middleware

**Comment by rafatower** [comment]
sorry, I misunderstood your point.

I'm taking care of this now...
