### ISSUE TITLE
Expose particular geocoder functions in the public API

### ISSUE THREAD

**Issue by rafatower** [CartoDB/dataservices-api#209]
In particular the following functions:
```
cdb_dataservices_server._cdb_here_geocode_street_point
cdb_dataservices_server._cdb_google_geocode_street_point
cdb_dataservices_server._cdb_mapzen_geocode_street_point
```

Quota/config checks should still apply but let for instance a user with `here` by default use explicitly `mapzen` or `here`.

See https://github.com/CartoDB/dataservices-api/blob/development/server/extension/sql/20_geocode_street.sql

**UPDATE**: `cdb_dataservices_server._cdb_mapzen_geocode_street_point` is the priority

**Comment by rafatower** [comment]
cc/ @javisantana (for the next milestone)

**Comment by iriberri** [comment]
Reopening. Still not in production. I'll close this manually, I'm starting the deploy right now.
