### ISSUE TITLE
Normalize for getmeasure should default to NULL

### ISSUE THREAD

**Issue by talos** [CartoDB/dataservices-api#235]
We handle the default for `normalize` further down the line by assuming it's `NULL`, but it's being defaulted to `area` in PL/Proxy:

https://github.com/CartoDB/dataservices-api/blob/d57856367a0d2a131d6e0285d7e5fec673a39f66/server/extension/sql/110_data_observatory_augmentation.sql#L226

This produces unexpected behavior (normalization by area) which is different than expected according to documentation for polygons: https://carto.com/docs/carto-engine/data/measures-functions/#obsgetmeasurepolygon-geometry-measureid-text

> for measures that are are sums (e.g. population) the default normalization is ‘none’ and response comes back as a raw value. Other options are ‘denominator’, which will use the denominator specified in the Data Catalog (optional)

A simple one-line change should suffice, but it might cause test failures down the line.  CC @iriberri , let me know if you want me to make a PR right now with that one line change.

**Comment by iriberri** [comment]
It seems there are a lot of hardcoded default even in the client: https://github.com/CartoDB/dataservices-api/blob/15eb8633d78f8ea6ecf2c53f97681b2e2ec30a4c/client/renderer/interface.yaml#L294

**Comment by talos** [comment]
OK... I'll take a look through tonight and see if I can fix them all, then cross-reference against the tests and ID the ones that may fail now.
