### ISSUE TITLE
Localization for geocoding

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/dataservices-api#251]
We may have different names for the same place even in the official language(s) of the country, having a strict match to geocode leads to many fails and "holes" in the results. V.g.: 
* Gipuzkoa <> Guipúzcoa
* Xaló <> Jalón
* A Coruña <> La Coruña

Maybe we should make use of fuzzy search like tsvector or trigrams

Tsvector sample pseudocode:

```sql
SELECT 
the_geom
FROM
geometries_table
ORDER BY
ts_rank(to_tsvector(storedname),to_tsquery(inputname))
ASC
LIMIT 1;
```

It would be much faster if we precompute a tsvector column in the geometries table.

cc @talos

**Comment by ethervoid** [comment]
For our internal geocoder we have synonym tables for this kind of situations. https://github.com/CartoDB/data-services/blob/cf2feaf4032579ff82f3b48d1fe32d4fcf108346/geocoder/extension/sql/0.0.1/20_admin0.sql#L11

I think this is what you're talking about.

**Comment by AbelVM** [comment]
The problem I see in synonyms table is maintenance. Names changes from time to time, or a new country or level of detail is added. 

Example: As of today, loading a CSV with provinces of Spain produces holes always due to accents (accents in uppercase are not compulsory, so JAEN <> Jaén), articles, and the different co-official languages in different regions.

**Comment by ethervoid** [comment]
Then this should go to https://github.com/CartoDB/data-services because there is where the internal geocoder functions are.

**Comment by AbelVM** [comment]
https://github.com/CartoDB/data-services/issues/221
