### ISSUE TITLE
Release a production ready table level function for Observatory measures

### ISSUE THREAD

**Issue by iriberri** [CartoDB/dataservices-api#258]
Opening the issue to track all the details to be improved/done:

* [x] Rename framework functions to `DST_X`, not `OBS_X`
* [x] [OBS] Abstract query generation to functions independent of infrastructure
* [x] [OBS] Abstract metadata information to functions independent of infrastructure
* [ ] ~~[OBS] Test with query generation (text) and calling another internal function which will give results for each type of query~~

Observatory PR: https://github.com/CartoDB/observatory-extension/pull/186
DS PR:  https://github.com/CartoDB/dataservices-api/pull/259

**Comment by iriberri** [comment]
@rafatower @ethervoid, your input on the both PRs linked above (especially OBS) would be appreciated :)

I have some unit tests pending to push for the new functions that I've added in the observatory that I have been using to test the new structure, but it's still quite open to changes so I didn't want to mess with tests in the PR.

**Comment by iriberri** [comment]
I'm currently checking the approach of running internal functions to retrieve the data in observatory and basically this implies adding a "SELECT * FROM OBS_GetMeasureData(...)" which returns records, so we would have to add the complexity of casting the records and selecting them in the observatory too. Right now this is what the DS client does, but if we add an extra level of abstraction to get the data, that query would require to be surrounded by the casting complexity. At this point I think that receiving the query and returning the records is simpler.

**Comment by iriberri** [comment]
We should be adding quota checks ASAP here, right? Otherwise this is an "open door" to the observatory.

**Comment by rafatower** [comment]
We're not in a rush to add quota checks, but to make sure they can be added.
