### ISSUE TITLE
More precise tracking of OBS usage

### ISSUE THREAD

**Issue by talos** [CartoDB/dataservices-api#260]
Right now, we keep track of usage of the Observatory user-by-user/org-by-org in order to make sure nobody exceeds their quota.

For the purpose of determining which API components and data components of the OBS are being used, though, we would like to think through how we could track the following:
- How much each API functions was called (`OBS_GetMeasure`, `OBS_GetBoundaryById`, etc.)
- Which arguments were passed to the functions (`us.census.tiger.block_group_clipped`, `us.census.acs.B03002006`, `area`, etc.)

It would be ideal to also be able to tie these calls back to users.

This should already be logged somewhere, but as part of a firehose with lots of other data mixed in.

Since we don't need to take any app-logic action based off these numbers, this tracking could probably be accomplished by piping the relevant logs somewhere else, and then having a separate process package and store the summary of those logs on a schedule.  We don't need to store this in a proper DB or deal with that associated overhead.

Curious for your thoughts @rafatower on how doable this is with our current infrastructure.  If it was safe for us to have access to OBS-specific logs (I'm imagining maybe a `tee` + `grep`), then we could probably put together the functions that would process and summarize the logs.

**Comment by talos** [comment]
RE https://github.com/CartoDB/cartodb-management/issues/4562

**Comment by rafatower** [comment]
@jmartinter who is in charge of metrics

**Comment by hannahblue** [comment]
Not sure if there's a more recent conversation around this, but we do need to start tracking DO API usage. 

@juanignaciosl, @ethervoid, @msaenzde11 I think we've each spoken briefly about this on various occasions. How much effort do you think would be required to start reporting on this? 

cc @kevin-reilly

**Comment by lekum** [comment]
On principle the staging metrics flow and Kibana visualization is restored as described in https://github.com/CartoDB/cartodb-platform/issues/3752

Take on account that we have metrics only from yesterday and today.

Please reopen the issue with more information should you find any problem with the metrics system.

**Comment by antoniocarlon** [comment]
Currently the observatory functions have a call to a [`metrics` function](https://github.com/CartoDB/dataservices-api/blob/development/server/lib/python/cartodb_services/cartodb_services/metrics/log.py) for example [here](https://github.com/CartoDB/dataservices-api/blob/development/server/extension/sql/110_data_observatory_augmentation.sql#L275). These metrics are accesible using Kibana.

The idea is to add new parameters to the `metrics` function creating a new logger to receive the input parameters of the observatory functions to be able to identify numerators, denominators and so on and extract useful information using the Kibana dashboards.
