### ISSUE TITLE
Normalization default fixes may not be deployed

### ISSUE THREAD

**Issue by talos** [CartoDB/dataservices-api#261]
This should have been dealt with in https://github.com/CartoDB/dataservices-api/pull/237, but geometries are still defaulting to area instead of no normalization in `OBS_GetMeasure`.

As an example, if this is executed using raw SQL + the current version of observatory-extension:

```
gis=# select cdb_observatory.obs_getmeasure(st_buffer(st_setsrid(st_makepoint(-74.1, 40.7), 4326), 0.01), 'us.census.acs.B01003001', null, null, null);
  obs_getmeasure
------------------
 23272.4938451551
(1 row)

gis=# select cdb_observatory.obs_getmeasure(st_buffer(st_setsrid(st_makepoint(-74.1, 40.7), 4326), 0.05), 'us.census.acs.B01003001', null, null, null);
  obs_getmeasure
------------------
 197594.235995896
(1 row)
```

The smaller buffer yields a small number (~23K) and the larger buffer yields a larger number (~197K).  The exact same queries over the SQL API, however, yield:

http://jkrauss.cartodb.com/api/v2/sql?q=select%20obs_getmeasure(st_buffer(st_setsrid(st_makepoint(-74.1,%2040.7),%204326),%200.05),%20%27us.census.acs.B01003001%27):

```
{
    "obs_getmeasure": ​7942.09888321129
}
```

http://jkrauss.cartodb.com/api/v2/sql?q=select%20obs_getmeasure(st_buffer(st_setsrid(st_makepoint(-74.1,%2040.7),%204326),%200.05),%20%27us.census.acs.B01003001%27)

```
    {
        "obs_getmeasure": ​2697.83916407126
    }
```

These numbers are identical to what you'd get running locally, but explicitly specifying `'area'` as the normalization. 

I included the `NULL, NULL, NULL` arguments in the local example but not the remote because the dataservices-api wrapper should add those automatically if it's behaving well.  I get the desired behavior from dataservices-api if I specify them explicitly, but users should not need to.  If I do not specify them locally, I get the same (correct) behavior.

Perhaps something was not deployed @ethervoid ?

**Comment by iriberri** [comment]
Checking this

**Comment by ethervoid** [comment]
Found the problem. It seems like the team database is running the previous version. I'm going to check why the job didn't install the extension in out database. Maybe is not in the chef role

**Comment by ethervoid** [comment]
All right...I haven't updated the rails part that's why when we create a new user we're changing to the previous version. Fixing...

**Comment by ethervoid** [comment]
Should be fixed by now

**Comment by talos** [comment]
LGTM -- thank you! 👍
