### ISSUE TITLE
OBS quota is incremented even in cases when long-running query fails

### ISSUE THREAD

**Issue by talos** [CartoDB/dataservices-api#276]
We had a user report of having pretty much immediately run out of Observatory credits.

What happened is they attempted to augment a map of US census tracts (~74K).  They never got any results, but it did use up all their credits.

**Comment by talos** [comment]
A stopgap which will help prevent anyone from doing this accidentally: https://github.com/CartoDB/cartodb/issues/9798

**Comment by iriberri** [comment]
Yep, we are aware of this scenario, unfortunately. It'll happen with any of the functions of the API.

cc @rafatower @ethervoid

**Comment by ethervoid** [comment]
Yes, right now it happens with every row-level function, due to the whole operation occurs inside a transaction so if something goes wrong, a.k.a raise an exception, the whole transaction is rollbacked but the quota operations have been made. 

This is a known issue since the design and we should fix it in a soon time.

**Comment by talos** [comment]
Makes sense.  The stopgap mentioned above (cartodb/cartodb#9798) would mitigate this really well.

**Comment by saleiva** [comment]
yep, if not, for the time being, we could give credits back if it fails... at the end of the transaction

**Comment by talos** [comment]
It's a no-brainer (conceptually) to give credits back if there's a rollback.  But what if there's a timeout on the client side?  Would that trigger a rollback, or would the transaction complete server-side and still charge the credits?

**Comment by saleiva** [comment]
yep, its clearly a workaround
