### ISSUE TITLE
Wrapper function for obs_getlegacymetadata

### ISSUE THREAD

**Issue by talos** [CartoDB/dataservices-api#286]
The function is now deployed via https://github.com/CartoDB/observatory-extension/pull/202, but has no dataservices wrapper.

Should be straightforward to implement.  The only argument should default to `NULL`, and the observatory-extension function is safe to pass `NULL` into.

It's not possible to work on https://github.com/CartoDB/cartodb-platform/issues/2511 until the wrapper is written & deployed.

**Comment by talos** [comment]
The function that needs to be wrapped is [here](https://github.com/CartoDB/observatory-extension/blob/develop/src/pg/sql/42_observatory_exploration.sql#L292).

**Comment by talos** [comment]
@rafatower It would be good to get this scheduled soon, as that will let us finally remove our dependency on observatory.carto.com in the Builder.

**Comment by rafatower** [comment]
Okay, thanks for the prompt response. I scheduled this to be done after the rollout. Thank you!

**Comment by talos** [comment]
👍

**Comment by javisantana** [comment]
one question, why legacy?

**Comment by talos** [comment]
Because we should move over to using the API functions mentioned here https://github.com/CartoDB/dataservices-api/issues/287 for future Observatory interfaces.

This "legacy" function works with our existing interface, but does not expose a large amount of valuable metadata (timespans, filtering, etc.) that the above do.  The above were designed to power the interface sketched here https://github.com/CartoDB/design/issues/104#issuecomment-242414394 , which should also be the basis for Analysis in the future.

**Comment by javisantana** [comment]
ok thanks, so in the frontend migration I propose use #287 functions and not use the legacy one

**Comment by talos** [comment]
Yes.  And happy to do whatever coordination possible to make sure those new functions fulfill all requirements.

**Comment by rafatower** [comment]
I'd wait for #287 and close this issue

**Comment by rafatower** [comment]
Closing this and scheduling the other set of functions in #287 for the next sprint. Feel free to reopen it if for some reason you don't agree

**Comment by talos** [comment]
@rafatower sounds good to me as @javisantana has committed to writing new frontend code to consume the new APIs. :)

**Comment by rafatower** [comment]
Finally reopened. As @ethervoid pointed out this is a faster way of getting it integrated.
