### ISSUE TITLE
Wrapper functions for dimensional obs_meta calls

### ISSUE THREAD

**Issue by talos** [CartoDB/dataservices-api#287]
As part of https://github.com/CartoDB/observatory-extension/pull/202, we deployed new "dimensional" metadata functions that will be used to populate drop-downs allowing users to select their numerator, normalization, timespan and geometry.

These need to be wrapped to make them accessible to users.  The full list of functions is:
- [ ] [OBS_GetAvailableNumerators](https://github.com/CartoDB/observatory-extension/blob/develop/src/pg/sql/42_observatory_exploration.sql#L127)
- [ ] [OBS_GetAvailableDenominators](https://github.com/CartoDB/observatory-extension/blob/develop/src/pg/sql/42_observatory_exploration.sql#L184)
- [ ] [OBS_GetAvailableGeometries](https://github.com/CartoDB/observatory-extension/blob/develop/src/pg/sql/42_observatory_exploration.sql#L241)
- [ ] [OBS_GetAvailableTimespans](https://github.com/CartoDB/observatory-extension/blob/develop/src/pg/sql/42_observatory_exploration.sql#L292)

**Comment by saleiva** [comment]
related with https://github.com/CartoDB/cartodb/issues/9991
