### ISSUE TITLE
Unexpected/incorrect result for AOI drive times

### ISSUE THREAD

**Issue by mbforr** [CartoDB/dataservices-api#297]
Running into an error on my account with drive times. They show up in weird shapes like below - for long ranges (like 1 hour) and short ones (like 5 minutes) 

![screen shot 2016-10-27 at 9 30 52 am](https://cloud.githubusercontent.com/assets/4828460/19769214/81ee1bcc-9c28-11e6-9998-3ee15ead89b8.png)

![screen shot 2016-10-27 at 9 37 56 am](https://cloud.githubusercontent.com/assets/4828460/19769349/11bfeaa0-9c29-11e6-9a70-041d9b4afe7d.png)

**Comment by rochoa** [comment]
@mbforr Is this still happening?

**Comment by ethervoid** [comment]
This issue is inactive for a great amount of time. Closing it, if it still happens please reopen it.
