### ISSUE TITLE
MapInfo File Format Support

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/dataservices-api#304]
**Support Bee:** 10454518

A user is asking in Support if we support MapInfo file format. This is not a supported file format listed on our site. Testing with a zipped MapInfo file successfully imports. 

**In GitHub, it appears we support MapInfo:**
https://github.com/CartoDB/cartodb/blob/master/services/importer/spec/acceptance/mapinfo_spec.rb

**There is this sample import file in GitHub that I was able to test import successfully:**
https://github.com/CartoDB/cartodb/blob/master/services/importer/spec/fixtures/Ivanovo.zip

Should this info be added to our docs? 

Please let me know if I should open this issue elsewhere or assign to a different manager.

cc @CartoDB/support 
cc @csobier

**Comment by ztephm** [comment]
dupe of https://github.com/CartoDB/data-services/issues/223

**Comment by rafatower** [comment]
yes, it is supported and it should be documented.
