### ISSUE TITLE
Retries not working as expected

### ISSUE THREAD

**Issue by rafatower** [CartoDB/dataservices-api#317]
## Description of the problem

The issue is that some services are returning error responses sometimes and the `@qps_retry` is not working as expected. From the error log (see R/B 117):
```python
Traceback (most recent call last):
1 File "<string>" line 31 in __plpython_procedure__cdb_mapzen_isochrones_25880422 [locals]
2 File "/usr/local/lib/python2.7/dist-packages/cartodb_services/mapzen/qps.py" line 28 in wrapped_function [locals]
  'return QPSService(retry_timeout=timeout, querie...nd=qps).call(original_function, *args, **kwargs)'
3 File "/usr/local/lib/python2.7/dist-packages/cartodb_services/mapzen/qps.py" line 51 in call [args] [locals]
  self.retry(start_time, attempt_number)
4 File "/usr/local/lib/python2.7/dist-packages/cartodb_services/mapzen/qps.py" line 59 in retry [args] [locals]
  raise TimeoutException()
TimeoutException: 'Timeout requesting to mapzen server'
```

By inspecting the local variables, turns out that `retry_count	== 1`.

Taking a closer look to the code: https://github.com/CartoDB/dataservices-api/blob/a977bc97ab9add0040c66f1e3cdeaf61dff919e8/server/lib/python/cartodb_services/cartodb_services/mapzen/qps.py#L58

the problem there is that we're comparing the elapsed time in microseconds with the timeout in miliseconds. Using the default timeout, it will indeed fail with a `TimeoutException` if the first request takes more than `60 ms`.

## Tasks
- [x] Fix the QPS logic - DONE in #318
- [x] Discuss the PR #315 and the need of python `requests` lib retries cc/ @ethervoid

**Comment by ethervoid** [comment]
About the `requests` retries are the cleanest way to retry timeouts that we're suffering for. From the requests documentation:
```
Note, this applies only to failed DNS lookups, socket connections and connection timeouts, never to requests where data has made it to the server
```
This change is not related to the QPS part, they're different measures for different problems

**Comment by rafatower** [comment]
:+1: Then it makes all the sense. I was wondering if that could cause a burst of requests faster than the allowed QPS. Thanks for pointing out

**Comment by rafatower** [comment]
So, for consistency I'd revert this line: https://github.com/CartoDB/dataservices-api/pull/318/files#diff-82b4d24735e8e5a9f7fa4bf44eaef74bR16

test and release a new version. cc/ @jgoizueta

**Comment by jgoizueta** [comment]
What about the change of `qps` to 7 here?: https://github.com/CartoDB/dataservices-api/pull/318/files#diff-82b4d24735e8e5a9f7fa4bf44eaef74bR28

**Comment by rafatower** [comment]
That's the current value they offer with our api keys. It shouldn't be hardcoded but as things stand now...

**Comment by ethervoid** [comment]
Yup, should come from DB config, we need a config for every service
