### ISSUE TITLE
Implement mapzen structured geocoding

### ISSUE THREAD

**Issue by rafatower** [CartoDB/dataservices-api#319]
Implement this: https://mapzen.com/blog/structured-geocoding/

Some extra requirements:
- [ ] Add a configuration flag to switch from current to new implementation and back easily
- [ ] Test for platform limits (qps and the like) before enabling it widely
- [ ] Evaluate accuracy before enabling it widely

**Comment by rafatower** [comment]
This is important if we want the street level geocode to work properly with the Mapzen provider. See this screenshot:

![image](https://cloud.githubusercontent.com/assets/1914276/21640577/a4c41a28-d276-11e6-9fe9-f96a1335d1c3.png)

cc/ @saleiva for prioritization

**Comment by saleiva** [comment]
Do you need any help or change in the UI?

**Comment by saleiva** [comment]
geocoding should be always a priority

**Comment by rafatower** [comment]
Added to the TODO then. No, I don't foresee any UI needs.

**Comment by saleiva** [comment]
hi guys, @jorgesancha especially, Trying to get this into your head so we can prioritize please. Remember everything related with geocoder is key!

**Comment by rafatower** [comment]
@saleiva I deprioritized this in favor of another [issue](https://github.com/CartoDB/cartodb-management/issues/4821#issuecomment-280043870) in the board, which should have better cost/benefit ratio.

Given the size of the changes I'd re-evaluate this one after completing the other.

Hope you find it a sound decision :)

**Comment by saleiva** [comment]
I'd test the effects of that on other countries such as spain. I'm having
some wrong geocodes lately with data in spain

**Comment by ethervoid** [comment]
Closing because we're not using Mapzen as provider anymore
