### ISSUE TITLE
Check quota fails in some cases with period_end_date

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/dataservices-api#322]
There is a bug with the check quota dates [here](https://github.com/CartoDB/dataservices-api/blob/development/server/lib/python/cartodb_services/cartodb_services/metrics/user.py#L144-L148).

Basically if, for example, we take a period_end_date of `2016-08-31 13:59:49+00:00` that piece of code for today (2016-12-13 13:59:49+00:00) is trying to create a billing cycle from 2016-11-31 to 2016-12-31 which is not possible because November has 30 days.

This leads to `ValueError: day is out of range for month`

As acceptance, we should check and add tests for 30 days months and for February.

**Comment by jgoizueta** [comment]
I'm leaving this notes here about a brief look I took at this yesterday for whoever may need it:

```python
import calendar
def last_day_of_month(y, m):
  return calendar.monthrange(y, m)[1];
```

Then we can use it to construct dates like so:

```python
date(temp_date.year, temp_date.month, min(end_period_day, last_day_of_month(temp_date.year, temp_date.month)
```

We should add tests for these cases and look for other places where this could be happening.

**Comment by rafatower** [comment]
This is the classical one I'd tackle with TDD, but just my opinion.

**Comment by jgoizueta** [comment]
Totally agree

**Comment by rafatower** [comment]
After raising the quota the integration/regression tests look fine.
