### ISSUE TITLE
Prevent type "geometry" does not exist when upgrading

### ISSUE THREAD

**Issue by rafatower** [CartoDB/dataservices-api#324]
When upgrading the extension we're getting some instances of `type "geometry" does not exist`. This happens because though the `geometry` type should be in the `search_path`, it is not.

My workaround for this was to edit the extension sql file and add this to the top:
```
SET search_path = "$user",public, cdb_dataservices_client;
```

Instead of that, it is best to add the schema explicitly and forget about this issue. (There's an issue related to this and moving extensions to different schemas but maybe not worth pursuing? I'll try to find and link here)

**Comment by rafatower** [comment]
One of those errors:
```
[dbd-talos.useb.cartodb.net] out: 2016/12/15 12:26:58 [ERROR] [cartodb_user_d377e55d-4326-4faf-97c7-503535e81667_db pq: type "geometry" does not exist]
```

and investigating it a little:
```
cartodb_user_d377e55d-4326-4faf-97c7-503535e81667_db=# \dx
                                                   List of installed extensions
          Name           | Version |         Schema          |                             Description                             
-------------------------+---------+-------------------------+---------------------------------------------------------------------
 cartodb                 | 0.18.5  | cartodb                 | Turn a database into a cartodb user database.
 cdb_dataservices_client | 0.13.0  | cdb_dataservices_client | CartoDB dataservices client API extension
 crankshaft              | 0.5.1   | cdb_crankshaft          | CartoDB Spatial Analysis extension
 observatory             | dev     | cdb_observatory         | CartoDB Observatory backend extension
 odbc_fdw                | 0.2.0   | public                  | Foreign data wrapper for accessing remote databases using ODBC
 plpgsql                 | 1.0     | pg_catalog              | PL/pgSQL procedural language
 plproxy                 | 2.6.0   | observatory             | Database partitioning implemented as procedural language
 plpythonu               | 1.0     | pg_catalog              | PL/PythonU untrusted procedural language
 postgis                 | 2.2.2   | public                  | PostGIS geometry, geography, and raster spatial types and functions
 postgis_topology        | 2.2.2   | topology                | PostGIS topology spatial types and functions
 postgres_fdw            | 1.0     | public                  | foreign-data wrapper for remote PostgreSQL servers
(11 rows)
```
ok, postgis is there.

```
cartodb_user_d377e55d-4326-4faf-97c7-503535e81667_db=# \dT geometry
                     List of data types
 Schema |   Name   |               Description               
--------+----------+-----------------------------------------
 public | geometry | postgis type: Planar spatial data type.
(1 row)

cartodb_user_d377e55d-4326-4faf-97c7-503535e81667_db=# show search_path ;
                search_path                 
--------------------------------------------
 "$user", public, cartodb, topology, public
(1 row)

cartodb_user_d377e55d-4326-4faf-97c7-503535e81667_db=# alter extension cdb_dataservices_client update to '0.14.0';
ERROR:  type "geometry" does not exist
```

the error seems to happen within the extension code.

**Comment by rafatower** [comment]
It was actually a problem with the upgrade/downgrade:
```
cartodb_user_d377e55d-4326-4faf-97c7-503535e81667_db=# drop extension cdb_dataservices_client ;
DROP EXTENSION
cartodb_user_d377e55d-4326-4faf-97c7-503535e81667_db=# create extension cdb_dataservices_client ;
CREATE EXTENSION
```

that means that somehow we need to be extra-careful with those scripts. I'll try to check the specifics and share my findings with the rest of the team.

**Comment by rafatower** [comment]
For the record, the problem was spottend when releasing this PR: https://github.com/CartoDB/dataservices-api/pull/323

The upgrade file to blame: https://github.com/CartoDB/dataservices-api/blob/5b8fd70bdd351fb7a949ad588a81dde0821614a6/client/cdb_dataservices_client--0.13.0--0.14.0.sql

**Comment by rafatower** [comment]
@CartoDB/dataservices I cannot think of a reason for this bug to happen. I suggest a preventive fix adding that line to all client templates. If you can come up with a better idea...

**Comment by jgoizueta** [comment]
I've tried updating from 0.13.0 to 0.14.0 in a local environment with the same weird search path as in the error example above: `"$user", public, cartodb, topology, public` and it worked flawlessly.
So, still no idea what can be causing this.

**Comment by jgoizueta** [comment]
I don't know how this could have any relation to the problem, but I've noticed in the error example that the `plproxy` extension is in the `observatory` schema instead of in `public`.

**Comment by jgoizueta** [comment]
For the client I'd make this changes:

```diff
diff --git a/client/sql/00_header.sql b/client/sql/00_header.sql
index 65eb4bf..b41a51c 100644
--- a/client/sql/00_header.sql
+++ b/client/sql/00_header.sql
@@ -1,3 +1,6 @@
 --DO NOT MODIFY THIS FILE, IT IS GENERATED AUTOMATICALLY FROM SOURCES
 -- Complain if script is sourced in psql, rather than via CREATE EXTENSION
 \echo Use "CREATE EXTENSION cdb_dataservices_client" to load this file. \quit
+
+-- Make sure we have a sane search path to create/update the extension
+SET search_path = "$user",public,cdb_dataservices_client;
diff --git a/client/upgrade_downgrade_template.erb b/client/upgrade_downgrade_template.erb
index bc8eb7c..31be973 100644
--- a/client/upgrade_downgrade_template.erb
+++ b/client/upgrade_downgrade_template.erb
@@ -2,4 +2,7 @@
 -- Complain if script is sourced in psql, rather than via CREATE EXTENSION
 \echo Use "ALTER EXTENSION cdb_dataservices_client UPDATE TO '<%= version %>'" to load this file. \quit

+-- Make sure we have a sane search path to create/update the extension
+SET search_path = "$user",public,cdb_dataservices_client;
+
 -- HERE goes your code to upgrade/downgrade
```

So that the extension SQL script sets the search path at the top, and also the stub for the upgrade/down scripts also have it.

@rafatower @ethervoid do you think we should do the same for the server extension?

**Comment by ethervoid** [comment]
I'll not do that because in the future if we have more extensions we want to add to the search_path, most of the time that change is done via `db_service.rb`, we need to add it here and not all the developers are aware of the existence of this code.

**Comment by jgoizueta** [comment]
But the change of the search_path at the top of the extension script will only affect extension installation/update. I won't affect any user db session, will it? Then we can safely set up the search_path for our extension dependencies here, independently of any other extensions added in `db_services` which will be dependencies of other components.

Maybe I'm missing something, what do you think?

**Comment by ethervoid** [comment]
Hum, you're right SET command is temporary so this solution should fix the problem. :)

**Comment by jgoizueta** [comment]
I tested this in a development environment (creating a release with no other changes and upgrading/installing it).

Now we have two options to "deploy" this preventive fix:

* Just merge the changes into development/master so that next release will use it
* Do a new "empty" release (migration scripts will contain only the search_path header) and deploy it in production

Personally I think either way would be OK for this case. Any opinions to prefer one or the other?

**Comment by rafatower** [comment]
What I'd do, for consistency:
1. merge the PR
1. create a new (empty) version of the client in master.
1. test the upgrade and creation from scratch in staging as acceptance
1. leave it in acceptance until someone of us can pay attention to a rather easy deploy (but not today).

**Comment by jgoizueta** [comment]
I've accomplished points 1 to 3.

The deployment process appears as failed because of a bogus host, but it was succesfull otherwise.
The extension was successfully updated, then dropped/created for a single user, then the integration test ran for that user.

Note that the master branch now contains the release 0.14.1 used for the acceptance test.

**Comment by rafatower** [comment]
Deploy stopped because of this: https://github.com/CartoDB/cartodb-platform/issues/2918

**Comment by rafatower** [comment]
Found another issue testing in staging:
```
cartodb_staging_user_109cedd0-f6f2-4df7-9fac-9610be46bdd6_db=# create extension cdb_dataservices_client;
ERROR:  type "geometry" does not exist
cartodb_staging_user_109cedd0-f6f2-4df7-9fac-9610be46bdd6_db=# \dT *.geometry
                      List of data types
 Schema  |   Name   |               Description               
---------+----------+-----------------------------------------
 cartodb | geometry | postgis type: Planar spatial data type.
(1 row)
```

I think this is due to moving users to their own schemas and that situation does not happen anymore in production.
