### ISSUE TITLE
Soft limit is not working for functions

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/dataservices-api#326]
### Context
*Please explain here below what you were doing when the issue happened*

 @ramiroaznar was trying to generate routing for a 40k points dataset using the `cdbsol-admin`. He got a `You reached your quota limit` error message.

I activated for him soft limit for all the services without any change in the final result, the same error message. 

I checked for the service quota info:

```
    service     | monthly_quota | used_quota | soft_limit |     provider
----------------+---------------+------------+------------+------------------
 isolines       |         10000 |          0 | f          | heremaps
 hires_geocoder |        100000 |         25 | f          | mapzen
 routing        |         10000 |      10004 | f          | mapzen
 observatory    |       1000000 |      17115 | f          | data observatory
(4 rows)
```

So looks like we have some issue with the soft limits

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Activate soft limit for a data-services service
2. Try to execute a function without quota

### Current Result
*Please describe here below the current result you got*

 You get an exhausted quota error message

### Expected result
*Please describe here below what should be the expected behavior*

Function returns an results without problem

**Comment by rafatower** [comment]
remember that it may happen that the user config is cached for a while

**Comment by ethervoid** [comment]
I checked again the same user with identical outcome

**Comment by ethervoid** [comment]
For the record here is the metadata info:
```
"soft_obs_general_limit"
"true"
"soft_obs_snapshot_limit"
"false"
"soft_here_isolines_limit"
"true"
"soft_geocoding_limit"
"true"
"soft_mapzen_routing_limit"
"true"
```

**Comment by ethervoid** [comment]
I've checked in staging and it's working fine. Closing this ticket
