### ISSUE TITLE
Deploy major improvements to Observatory performance

### ISSUE THREAD

**Issue by talos** [CartoDB/dataservices-api#340]
### What we achieve

Deploy observatory-extension 1.3.0, which includes `OBS_GetData` and `OBS_GetMeta`, and then a new version of dataservices-api that wraps these two new functions.

* https://github.com/CartoDB/observatory-extension/pull/246/
* https://github.com/CartoDB/dataservices-api/pull/339

### Why

`OBS_GetData` and `OBS_GetMeta` provide a far more flexible and performant API for internal and external users to build off.  In particular:

* Considerable performance improvements for `OBS_GetMeasure` as used in the Builder UI
* Support for obtaining metadata for X columns and Y rows in 1 request, instead of X * Y requests
* Support for obtaining data for X columns and Y rows in 1 request, instead of X * Y requests

### Impact

* Immediate 20-30% speedup for existing OBS analysis
* After an update to Camshaft node, somewhere between a 3x and a 30x speedup for existing OBS interface
* Support for next-gen Observatory interface, which supports X columns at once (thus reducing strain on our servers & increasing usability immensely)

### Acceptance criteria

* Existing analysis in the UI continues to work
* Existing functions exposed via API for OBS still work as before (these are automatically tested)
* OBS_GetData and OBS_GetMeta work in user accounts

@ethervoid

**Comment by talos** [comment]
(We should do this while I'm here)

**Comment by ethervoid** [comment]
//cc @rafatower @rochoa

**Comment by rafatower** [comment]
Added to the TODO as per our conversation. Yes, please, let's take advantage of working on the same timezone.

It is worth noting that the two tasks must go one after another in the order of the description.

@talos it'd be nice to cover in the issue description, very briefly, the following items: 
- what we try to achieve
- why
- impact
- acceptance criteria

so that anyone looking at the [Engine dashboard](https://github.com/orgs/CartoDB/projects/3#card-1489082) understands why we tackle it before other issues and hopefully other people on the team can contribute to get it to the Done column.

**Comment by talos** [comment]
Yes, no problem.  Sorry for the brief description, I did not realize the purpose was to make the issue understandable more broadly -- now I understand.

### What we achieve

Deployment of observatory-extension 1.3.0, which includes `OBS_GetData` and `OBS_GetMeta`, and then a new version of dataservices-api that wraps these two new functions.

### Why

`OBS_GetData` and `OBS_GetMeta` provide a far more flexible and performant API for internal and external users to build off.  In particular:

* Considerable performance improvements for `OBS_GetMeasure` as used in the Builder UI
* Support for obtaining metadata for X columns and Y rows in 1 request, instead of X * Y requests
* Support for obtaining data for X columns and Y rows in 1 request, instead of X * Y requests

### Impact

* Immediate 20-30% speedup for existing OBS analysis
* After an update to Camshaft node, somewhere between a 3x and a 30x speedup for existing OBS interface
* Support for next-gen Observatory interface, which supports X columns at once (thus reducing strain on our servers & increasing usability immensely)

### Acceptance criteria

* Existing analysis in the UI continues to work
* Existing functions exposed via API for OBS still work as before (these are automatically tested)
* OBS_GetData and OBS_GetMeta work in user accounts

**Comment by rafatower** [comment]
@ethervoid Raul and I discussed this and told talos to assign it to you. If you absolutely cannot do it between today-tomorrow, please let me know and I'll handle this. Thanks!

**Comment by ethervoid** [comment]
Sure, on it

**Comment by ethervoid** [comment]
For the DS CR [this are the changes](https://github.com/CartoDB/dataservices-api/pull/339), right now are in development while I'm checking if works as should but in the meanwhile I'd love this to be CRed

**Comment by ethervoid** [comment]
Changes are done, removed quota usage for the OBS_Meta functions, moving to CR again. PR is #341

**Comment by ethervoid** [comment]
### Acceptance

The new release is deployed in rui01 - rui02 so you need a user there to do the acceptance

- First of all, execute all the integration tests that execute all the dataservices-api functions. You can execute them with [this Jenkins task](https://ci.cartodb.net/job/CartoDB-DATASERVICES-API-Integration-testing/)
- New functions shouldn't spend observatory credits so we need to check if we're using credits every time we call the functions. To check that, please:

  - Execute this query and check what is your user usage for `data_observatory`:

  ```
  https://{USERNAME}.carto-staging.com/api/v2/sql?q=select%20*%20from%20cdb_service_quota_info()&api_key={API_KEY}
  ``` 

  - Execute this OBS_GetData queries and check the used credits again:

  ```
  https://{USERNAME}.carto-staging.com/api/v1/sql?q=SELECT%20*%20FROM%20obs_getdata(ARRAY[%2736047%27],%20obs_getmeta(st_setsrid(st_point(-73.9,%2040.7),%204326),%20%27[{%22numer_id%22:%20%22us.census.acs.B01003001%22,%20%22geom_id%22:%20%22us.census.tiger.county%22}]%27,%201,%201,%201000))%20LIMIT%201;&api_key={API_KEY}
  https://{USERNAME}.carto-staging.com/api/v1/sql?q=SELECT%20id%20as%20data_id%20FROM%20obs_getdata(ARRAY[(ST_SetSRID(ST_Point(-73.9,%2040.7),%204326),%201)::geomval],%20obs_getmeta(st_setsrid(st_point(-73.9,%2040.7),%204326),%20%27[{%22numer_id%22:%20%22us.census.acs.B01003001%22}]%27))%20LIMIT%201;&api_key={API_KEY}
  ``` 

  - Execute this OBS_GetMeta query and check again if the quota increased:

  ```
  https://{USERNAME}.carto-staging.com/api/v1/sql?q=SELECT%20obs_getmeta(ST_SetSRID(ST_Point(-73.9,%2040.7),%204326),%20%27[{%22numer_id%22:%20%22us.census.acs.B01003001%22}]%27,%201,%201,%201000)%20LIMIT%201;&api_key={API_KEY}
  ```

**Comment by jgoizueta** [comment]
Acceptance results: \o/ it works!

I've checked (in a staging environment) that integration tests are passing (save expected exception described below), that `OBS_GetMeta` and `OBS_GetData` work, that the first doesn't consume any credits and that the latter does (and registers properly successful and empty results).

Some problems were found to run the tests (thanks to @ethervoid for his help!):

problems found during the tests (thanks to @ethervoid for sorting them out!):
* `obs_snapshot_quota` is required for some tests; it has no UI in central, so should be assigned from a box console:
  `Carto::User.find_by_username('USER').update_attributes!(obs_snapshot_quota: 10000)`
* Make sure the user database has the correct version of the ds api client: `ALTER EXTENSION cdb_dataservices_client UPDATE TO '0.15.0';
* The publicuser role in my user's db had an incorrect search_path that had to be fixed:
  `ALTER ROLE publicuser SET search_path = '"$user", public, cartodb, cdb_dataservices_client';`
* The integration tests executed by Jenkins come from the master branch of ds-api; so changes needed for this release are not present;
  in our case one test which used 2014 census data was affected.

**Comment by ethervoid** [comment]
Thank you very much!!!!

**Comment by ethervoid** [comment]
Deployed
