### ISSUE TITLE
Have DS row counts accessible in Kibana

### ISSUE THREAD

**Issue by talos** [CartoDB/dataservices-api#344]
### Summary

To understand the value and efficiency of API calls, we should expose the information from each API call about `processable_rows`, `successful_rows`, `failed_rows`, and `empty_rows`.

### Why we should do this

* Currently, our Kibana setup exposes metrics about the type of API call, when it happened, how long it took, who made it, etc, but does not reveal how many rows were returned or did not work
* We have several functions that return many rows, and without this capability we can't fully understand how people are using them (and are missing certain metrics to understand why something may perform a certain way)
* More specifically, as we move over Observatory functions to those that are not one-request-per-row, we will lose the ability to collect important data about usage.  https://github.com/CartoDB/camshaft/pull/254 is in the process of being merged, so this metrics regression is imminent

@rafatower is the expert on how this all works.  Hopefully the above is clear enough as to the goal, and I'm happy to clarify more.

**Comment by talos** [comment]
Assigning to @rochoa for coordination and prioritization.

**Comment by jorgesancha** [comment]
@kevin-reilly @juanignaciosl we are deprioritising this for the moment until we have a clear goal in sight as to what to do with that information.

**Comment by ethervoid** [comment]
Done
