### ISSUE TITLE
cdb_isochrones function returns extra row

### ISSUE THREAD

**Issue by michellemho** [CartoDB/dataservices-api#372]
Problem:
CDB_isochrone function appears to return an extra duplicate row with a null geometry when Mapzen isochrones is unable to create the isochrone.

Context:
I attempted to find an isochrone around a single point in rural Alaska by running the following code on [this table](https://team.carto.com/u/michellemho-carto/dataset/michellemho-carto.alaska_jcpenney).

```
SELECT 
(cdb_isochrone(the_geom, 'car', Array[600])).the_geom as the_geom,
status, distance, name, state_abb, total_pop_, total_pop_area_2011_2015, allhomes_z, closed_dat, phone, state, address, median_income_2011_2015
FROM
alaska_jcpenney
```
The result is an extra duplicate row:

![image](https://cloud.githubusercontent.com/assets/12551177/26463428/36d7c3ca-4152-11e7-840f-89bc52ea8e5b.png)

After some digging into the dataservices code with @talos, we think the code snippet that might be yielding the extra row can be found here:
https://github.com/CartoDB/dataservices-api/blob/4822739fee41843e6e5fc593944f93daffb60945/server/extension/sql/80_isolines_helper.sql#L167-L177

Related issue: https://github.com/CartoDB/dataservices-api/issues/365

**Comment by ethervoid** [comment]
Not happening with Mapbox, closing
