### ISSUE TITLE
[OBS] Replace obs_snapshot by obs_general in quota checks

### ISSUE THREAD

**Issue by rafatower** [CartoDB/dataservices-api#381]
In order to simplify the code and management of users, replace the deprecated obs_snapshot quota checks by obs_general.

Considering this a bug, since the documentation is not consistent with the behavior.

**Comment by rafatower** [comment]
https://github.com/CartoDB/dataservices-api/blob/402c14e6cabc1c9512d1fa59ab78fd12f0d1be63/server/lib/python/cartodb_services/cartodb_services/metrics/config.py#L89

**Comment by ethervoid** [comment]
Deployed
