### ISSUE TITLE
Fix google services secret key validity check

### ISSUE THREAD

**Issue by rafatower** [CartoDB/dataservices-api#382]
It turns out that the google keys are not strictly base64-encoded but a variant of it:

https://developers.google.com/maps/documentation/directions/get-api-key

> 3. Retrieve your private key, which is encoded in a modified Base64 for URLs, and sign the URL above using the HMAC-SHA1 algorithm. You may need to decode this key into its original binary format. Note that in most cryptographic libraries, the resulting signature will be in binary format.
>
> Note: Modified Base64 for URLs replaces the + and / characters of standard Base64 with - and _ respectively, so that these Base64 signatures no longer need to be URL-encoded.

Therefore this check fails if the key contains a dash (`-`) or underscore (`_`) character as they are not valid in standard base64 encoding:

https://github.com/CartoDB/dataservices-api/blob/402c14e6cabc1c9512d1fa59ab78fd12f0d1be63/server/lib/python/cartodb_services/cartodb_services/google/geocoder.py#L56-L64

(note: that is something that might have changed since it was implemented)

cc/ @ernesmb

**Comment by rochoa** [comment]
cc @juanignaciosl for awareness.

**Comment by rafatower** [comment]
Fixed in https://github.com/CartoDB/dataservices-api/pull/402
