### ISSUE TITLE
Upgrade google services client library to v2.5.1

### ISSUE THREAD

**Issue by rafatower** [CartoDB/dataservices-api#383]
While investigating an issue related to request signing and not being accepted by google services, we figured out that for some reason current google services client library was not producing valid signatures for requests issued from DS API when the secret key contains a dash character.

See this issue: https://github.com/CartoDB/dataservices-api/issues/382

Upgrading the `googlemaps` library fixed the problem.

The dependency  on the particular version of that library is coded here:
https://github.com/CartoDB/dataservices-api/blob/402c14e6cabc1c9512d1fa59ab78fd12f0d1be63/server/lib/python/cartodb_services/requirements.txt#L4

cc/ @ernesmb

**Comment by rafatower** [comment]
Mind that the configs shall be changed in the cookbooks for cloud and on-premise installs as well.

**Comment by rochoa** [comment]
cc @juanignaciosl for awareness.

**Comment by rafatower** [comment]
Actually we need to update the client because of some other reason: that version of the client is always establishing and tearing down connections, and that is the current performance bottleneck. Newer versions of the client maintain TCP keepalive connections and therefore do not need to reconnect.

See https://github.com/googlemaps/google-maps-services-python/issues/163 for more information.

**Comment by rafatower** [comment]
Reopening as I'm still fighting with python deps and cookbooks

**Comment by rafatower** [comment]
deployed, closing this now.
