### ISSUE TITLE
Client tests are broken in Jenkins

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/dataservices-api#385]
Between commit caf30e1bf66a9cac1ec2360e23b6046cc9d1d233 and cb5aa3e1afe6d41a80fc3910391981c3ab3b0f66 (which contains only doc changes) the client extension tests ran by ~~Travis~~ Jenkins CI have gone from green to red

I've rerun the tests for caf30e1bf66a9cac1ec2360e23b6046cc9d1d233 and now they fail, so it must be some change in the ~~Travis~~ Jenkins environment occurred between 2017-05-31 and 2017-06-28

**Comment by rochoa** [comment]
Travis?

**Comment by jgoizueta** [comment]
Sorry: mental lapse 😓 , it's our Jenkins task actually

**Comment by jgoizueta** [comment]
#386 seems to solve this. It seems some CONTEXT messages are no longer emitted. (my local environment must have some different PG logging configuration from the current one at travis and dev. environment provisioning)

**Comment by ethervoid** [comment]
This was solved isn't it?

**Comment by jgoizueta** [comment]
Yep, closing it.
