### ISSUE TITLE
Fix renaming of input parameter incompat issue

### ISSUE THREAD

**Issue by rafatower** [CartoDB/dataservices-api#417]
When trying to deploy `v0.22.0` of the client I'm getting the message:
    
```
cannot change name of input parameter "organization_name"
```

that comes from several functions:
```
cartodb_staging_user_548faa56-942d-41eb-8879-66ff7bad2227_db=# alter extension cdb_dataservices_client update to '0.22.0';
ERROR:  cannot change name of input parameter "organization_name"
HINT:  Use DROP FUNCTION _cdb_geocode_admin1_polygon(text,text,text) first.

[then fix manually and repeat]

cartodb_staging_user_548faa56-942d-41eb-8879-66ff7bad2227_db=# alter extension cdb_dataservices_client update to '0.22.0';
ERROR:  cannot change name of input parameter "organization_name"
HINT:  Use DROP FUNCTION _cdb_geocode_namedplace_point(text,text,text) first.

....
```

The problem was introduced by some changes in the templates 7101c8d8e8bcc4b5550eb53ec27dd7b24c3594c5

This is usually no big deal, but since we're touching pretty much all functions in `v0.22.0` we need to find a plausible approach to fix this.

cc/ @jgoizueta @Algunenano

**Comment by rafatower** [comment]
Note: this is my silly attempt at fixing it: 63786caaa68c8d958016eb5a879a02608b54ac39

already reverted (in development)

**Comment by rafatower** [comment]
Note II: the underlying problem is that going through different upgrade paths (`0.10.0--0.11.0--0.11.1--etc`) produces slightly different results depending on which updates you apply and what version you departed from.

**Comment by jgoizueta** [comment]
I think we can add this line at the top of `client/renderer/templates/30_plproxy_functions.erb`

```
DROP FUNCTION <%= DATASERVICES_CLIENT_SCHEMA %>._<%= name %> (<%= params_with_type_and_default(true).join(', ') %>);
```

We don't need to generate parameter names for the DROP declaration, types are enough, but I've checked in PG9.5 & PG10, and it seems that if you use them they don't need to match the names in the definition (as for CREATE OR REPLACE). This allows us to reuse `params_with_type_and_default()` and not have to defined a new function (`param_types()`) generate the function signature.

**Comment by rafatower** [comment]
### Acceptance
- Install v0.10.0: `CREATE EXTENSION cdb_dataservices_client WITH VERSION '0.10.0';`
- Try an update to v0.22.0: `ALTER EXTENSION cdb_dataservices_client UPDATE TO '0.22.0';`

Expected result: the extension is updated. Check with `\dx`

**Comment by rafatower** [comment]
```
contrib_regression=# CREATE EXTENSION cdb_dataservices_client WITH VERSION '0.10.0';
CREATE EXTENSION
contrib_regression=# alter extension cdb_dataservices_client update to '0.22.0';
ALTER EXTENSION
```
