### ISSUE TITLE
Mapbox geocoder issues with encoding

### ISSUE THREAD

**Issue by javitonino** [CartoDB/dataservices-api#433]
Using this `.carto` (basically a geocoding, with España as a country, followed by isolines)

[tabla_info_capas_xlsx_aloj_bares_rest_tur_act map (on 2018-01-29 at 15.54.23).carto.zip](https://github.com/CartoDB/dataservices-api/files/1674200/tabla_info_capas_xlsx_aloj_bares_rest_tur_act.map.on.2018-01-29.at.15.54.23.carto.zip)

https://rollbar.com/carto/Dataservices-API/items/269/
https://rollbar.com/carto/Dataservices-API/items/270/

**Comment by ethervoid** [comment]
We're using [this library](https://github.com/deactivated/python-iso3166) to get iso3166 value for a country and it doesn't support UTF8 characters. We should get the iso3 using the current functions and then use this library to get the iso2 value

// @antoniocarlon

**Comment by ethervoid** [comment]
Fixed
