### ISSUE TITLE
new routing distances in meter, docs says kilometers

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/dataservices-api#442]
The new routing provided by Mapbox appears to return distance measurements in meters ([mapbox docs](https://www.mapbox.com/api-documentation/#route-object)), while the old mapzen service returned values in kilometers (which is in our docs: https://carto.com/docs/carto-engine/dataservices-api/routing-functions/#cdb_route_point_to_pointorigin-geometrypoint-destination-geometrypoint-mode-text-options-text-units-text). 

The documentation needs to be updated to say `meters` (or the values returned via the `cdb_route_point_to_point` function should be converted to kilometers).

cc @ethervoid

**Comment by ethervoid** [comment]
I've been checking what kind of measure provides HERE for its routing types and is meters too, so we are changing the documentation to say meters instead of converting to kilometers just in case we provide HERE in the future

**Comment by ethervoid** [comment]
Fixed, take a look and thank you for reporting the problem :)
