### ISSUE TITLE
routing linestrings are not showing in the correct part of the world

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/dataservices-api#443]
Here are the points:

<img width="388" alt="screen shot 2018-01-31 at 16 10 37" src="https://user-images.githubusercontent.com/1041056/35647690-532daaa2-06a1-11e8-9520-429bb880937c.png">

Query to get that:

```sql
WITH cte as (
SELECT
        CDB_LatLng(40.8013053,-73.9715362) as the_geom, 1 as cartodb_id
UNION ALL
SELECT
        CDB_LatLng(40.7045402,-73.9388631), 2
  )
SELECT the_geom, st_transform(the_geom, 3857) as the_geom_webmercator, cartodb_id
FROM cte
```

And the resulting routing, which is centered at POINT(-7.3933296492208 4.0785607010735):
<img width="557" alt="screen shot 2018-01-31 at 16 15 43" src="https://user-images.githubusercontent.com/1041056/35647894-0938883a-06a2-11e8-915a-a1eec33d59ee.png">

And the query to get that routing:
```sql
with cte as (
    SELECT (cdb_route_point_to_point(
        CDB_LatLng(40.8013053,-73.9715362),
        CDB_LatLng(40.7045402,-73.9388631), 'car')).*
)
SELECT shape as the_geom, ST_Transform(shape, 3857) as the_geom_webmercator, 1 as cartodb_id
FROM cte
```
As you can see from the centroid of the linestring, the point `POINT(-7.3933296492208 4.0785607010735)` is about 1/10th of the lng and lat values, leading to routing that maps (lng, lats) -> (lng/10, lat/10)

cc @ethervoid

**Comment by ethervoid** [comment]
Deployed and fixed
