### ISSUE TITLE
Avoid logging out of quota errors

### ISSUE THREAD

**Issue by javitonino** [CartoDB/dataservices-api#446]
It doesn't make much sense to log those, since there is nothing we can do (user error) and it generates a lot of noise.

**Comment by ethervoid** [comment]
With the introduced changes we have the following response:

**Before**

```json
{
  "rows": [
    {
      "cdb_geocode_namedplace_point": "0101000020E61000006C04E275FD2213C00D6C956071D44440"
    }
  ],
  "time": 0.201,
  "fields": {
    "cdb_geocode_namedplace_point": {
      "type": "geometry"
    }
  },
  "total_rows": 1,
  "warnings": [
    "cdb_dataservices_client._cdb_geocode_namedplace_point(3): [cartodb_staging_user_fef64064-3754-40b4-9032-6f7d6cd95edf_db] REMOTE WARNING: Error geocoding namedplace using geocode street point, falling back to internal geocoder"
  ]
}
```

**After**
```json
{
  "rows": [
    {
      "cdb_geocode_namedplace_point": null
    }
  ],
  "time": 0.03,
  "fields": {
    "cdb_geocode_namedplace_point": {
      "type": "geometry"
    }
  },
  "total_rows": 1
}
```

Now we don't do fallback and we don't send the Quota exception to rollbar

**Comment by ethervoid** [comment]
FYI we have removed a part of the messages ( the geocoding ones ), to remove all the platform quota errors we need to keep moving forward with the migration to the refactor #449  but this fix sholud do the trick and remove a huge amount of them
