### ISSUE TITLE
Check how it works with PG10

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/dataservices-api#461]
Check how DS behaves using PG10

**Comment by ethervoid** [comment]
I've executed all the tests: client, server and library using pg10 and postgis 2.4 without problem

//cc @skgsergio

**Comment by skgsergio** [comment]
Thanks, in my CI tests the task weas failing. Since you double checked will see once we migrate CI (tomorrow).

**Comment by ethervoid** [comment]
@skgsergio Can you provide me access to check it, maybe my local copy is not working as intended or something just to double check

**Comment by ethervoid** [comment]
It's working fine. No tests failed with PG10
