### ISSUE TITLE
Compare Mapbox and Here Isochrones

### ISSUE THREAD

**Issue by hannahblue** [CartoDB/dataservices-api#489]
We are beginning to get complaints about isochrones. Let's compare Mapbox Isochrone results against Here results to determine if there are any improvements we can make to our implementation of the Mapbox isochrones. 
[Isochrone Example (on 2018-03-27 at 13.40.16).zip](https://github.com/CartoDB/dataservices-api/files/1852183/Isochrone.Example.on.2018-03-27.at.13.40.16.zip)

@juanignaciosl, @ethervoid

**Comment by antoniocarlon** [comment]
@hannahblue, now that the default isochrone is TomTom and it has proven to be between Mapbox and Here in terms of quality, can we close this issue?

**Comment by hannahblue** [comment]
Yep :)
