### ISSUE TITLE
Add TomTom

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/dataservices-api#492]
- [x] CartoDB/cartodb-platform/pull/4272
- [ ] CartoDB/dataservices-api/pull/466
- [ ] CartoDB/cartodb/pull/13821
- [ ] CartoDB/cartodb-central/pull/2195

cc @hannahblue

**Comment by juanignaciosl** [comment]
@hannahblue I think that having TomTom available deserves a [Product Updates blog entry](https://carto.com/product-updates/), do you agree?

**Comment by jorgesancha** [comment]
![yes](https://user-images.githubusercontent.com/86218/39762107-21094416-52da-11e8-8cf4-25aa7bb06e65.gif)

We need to be very clear as to who and how can activate this in the post

**Comment by hannahblue** [comment]
Aweome @juanignaciosl! Definitely need a blog post. I'm happy to write it, but I think @jorgesancha's vision was for the developer to write it themselves too. Let me know which you prefer.

**Comment by juanignaciosl** [comment]
Ok,, @hannahblue , I'll prepare it. Anyway, I'll need your help for commercial and financial details!!

**Comment by juanignaciosl** [comment]
CartoDB/product-updates/pull/16
