### ISSUE TITLE
10 million records to batch geocode - mapbox or data services api key?

### ISSUE THREAD

**Issue by orrholly** [CartoDB/dataservices-api#510]
American express needs to first geocode around 10 million records - merchants around the globe that accept American Express.

After the initial batch run, they will want to use the API to geocode the merchant data as they receive it - so not as much bandwidth or credits.

I have been told by Bizops we have a 2.5 million credit limit for geocoding per month using our data services api. Bizops thinks they can increase the limit during the limited time we need for the initial upload. But we do not know if there are bandwidth/latency issues when we use our data services key vs the mapbox key directly.

Timeline: I need to get back to Amex today with a test API key (mapbox or data services) and the appropriate documentation so they can get to know our product before they do the 10 million record batch geocoding.

Will the solution we choose influence which documentation we provide to the client - mapbox or Carto's data services? Are there nuances between the APIs and the queries used against them?

**Comment by juanignaciosl** [comment]
>  I need to get back to Amex today with a test API key (mapbox or data services) and the appropriate documentation so they can get to know our product before they do the 10 million record batch geocoding.

There's no such thing as a "Dataservices API key". Just signing up at CARTO grants a master API key that you can use for Dataservices API. And I don't think that we should give any of our Mapbox keys.

> Will the solution we choose influence which documentation we provide to the client - mapbox or Carto's data services? Are there nuances between the APIs and the queries used against them?

Of course. Since they're different APIs, requests are totally different. We can't give _our_ Mapbox keys. I don't know if we can buy new ones and resell.

**Comment by hannahblue** [comment]
@juanignaciosl, biz-ops can generate a Mapbox API key for them to use. As far as I understand they really just bought Mapbox directly from us in this deal (with a "proof of value", non-production carto license on the side). @bspiro can give more detail if needed.

**Comment by juanignaciosl** [comment]
Then, if they want to use their own key (which looks like a good choice), they just need [Mapbox Geocoding API documentation](https://www.mapbox.com/api-documentation/#geocoding).

If they wanted to use Dataservices API they can just [check our documentation](https://carto.com/location-data-services/geocoding/). Nevertheless, for such a huge amount of geocodings, I see little value on using our API. The recently released batching function is not meant to be used directly by users (at least, not yet). IIRC, in the past, in other similar situations (Brazil) solutions developed a custom script directly to the (HERE) API.

Is this enough from them? I don't know if we (product) are supposed to do more about this.

cc @luisbosque @rochoa

**Comment by juanignaciosl** [comment]
Some suggestions:
1.- (this is obvious) batch it, sorted, so you can easily resume.
2.- take advantage of [Mapbox batch API](https://www.mapbox.com/api-documentation/#batch-requests), you can get up to 50 geocodings in a single request.
3.- Group the batches by city and/or country and provide as much information as possible in the requests to get accurate results. During my tests for batching I saw some poor behaviour. Example: Valladolid is both the name of a province and the capital of the province (and it's, by far, the biggest city). Nevertheless, requesting "Plaza Mayor, Valladolid" returns a square at a small town ("Montemayor de Pililla"). You must ask for "Plaza Mayor, Valladolid, Valladolid" for mapbox to be accurate:

```curl
$ curl https://api.mapbox.com/geocoding/v5/mapbox.places-permanent/Plaza%20Mayor%2C%20Valladolid%2C%20es.json?access_token=XXXX | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3177  100  3177    0     0  16045      0 --:--:-- --:--:-- --:--:-- 16126
{
   "type" : "FeatureCollection",
   "attribution" : "© 2017 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service. (https://www.mapbox.com/about/maps/)",
   "features" : [
      {
         "relevance" : 1,
         "context" : [
            {
               "text" : "47320",
               "id" : "postcode.13218374747905950"
            },
            {
               "wikidata" : "Q1651701",
               "id" : "place.18511717392154610",
               "text" : "Montemayor de Pililla"
            },
            {
               "wikidata" : "Q71097",
               "short_code" : "ES-VA",
               "id" : "region.3207",
               "text" : "Valladolid"
            },


...

$ curl https://api.mapbox.com/geocoding/v5/mapbox.places-permanent/Plaza%20Mayor%2C%20Valladolid%2C%20Valladolid%2C%20es.json?access_token=XXX | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3049  100  3049    0     0  14247      0 --:--:-- --:--:-- --:--:-- 14314
{
   "features" : [
      {
         "geometry" : {
            "coordinates" : [
               -4.728732,
               41.651634
            ],
            "type" : "Point"
         },
         "context" : [
            {
               "id" : "postcode.10648000839984100",
               "text" : "47001"
            },
            {
               "id" : "place.5865738710560650",
               "text" : "Valladolid",
               "wikidata" : "Q8356"
            },
            {
               "short_code" : "ES-VA",
               "id" : "region.3207",
               "text" : "Valladolid",
               "wikidata" : "Q71097"
            },

```

**Comment by hannahblue** [comment]
Thanks @juanignaciosl! 

So with: 
- 10 million geocodes
- 50 geocodes per request
- 2400 requests per minute (for our entire account. We need to use less than this so that our other users aren't effected)

It'll be 200,000 (10m/ 50) requests.  If we did 1000 requests per minute it would take 3 1/3 hours (200/60) to get it done.

@juanignaciosl does that look right to you? Anything I'm missing?

**Comment by juanignaciosl** [comment]
Taken from [their docs](https://www.mapbox.com/api-documentation/#batch-requests): "Each query in a batch request counts individually against your account's rate limits.". So, according to that, no more than 2400/50 requests per minute can be done (for batches of 50).
