### ISSUE TITLE
Document and public release of batched geocoding

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/dataservices-api#531]
Document `cdb_bulk_geocode_street_point` as a public available function (and make announcement if needed).

cc @danicarrion @javitonino

**Comment by danicarrion** [comment]
@javitonino apart from documenting the function, is there anything else we need to be aware of before making this generally available? If it's only documenting the function, then maybe I can do that myself to finally close this.

**Comment by javitonino** [comment]
I think it's ok with just documenting it, we have been using it in production for months and I don't see a reason to keep it secret.

**Comment by danicarrion** [comment]
ok, I can work on that if that's ok

**Comment by danicarrion** [comment]
PR created.
