### ISSUE TITLE
Geocoding analyses creates table with wrong geometry type

### ISSUE THREAD

**Issue by javitonino** [CartoDB/dataservices-api#538]
STR:
1. Create a new empty dataset
2. Add a row, with some random address
3. Create a map from that dataset
4. Geocode it (street geocoder, mapbox).

Result:
```
       Table "javitonino.analysis_1ea6dec9f3_8588af2c0cd559ee83c218f244c6cb4ae2b1d6d0"
            Column            |            Type             | Collation | Nullable | Default 
------------------------------+-----------------------------+-----------+----------+---------
 cartodb_id                   | integer                     |           |          | 
 name                         | text                        |           |          | 
 description                  | text                        |           |          | 
 the_geom                     | geometry(MultiPolygon,4326) |           |          | 
 __geocoding_meta_relevance   | numeric                     |           |          | 
 __geocoding_meta_precision   | text                        |           |          | 
 __geocoding_meta_match_types | text[]                      |           |          | 


select ST_GeometryType(the_geom) FROM javitonino.analysis_1ea6dec9f3_8588af2c0cd559ee83c218f244c6cb4ae2b1d6d0;
 st_geometrytype 
-----------------
 ST_Point
 ST_Point
(2 rows)
```

Expected, table has `Point` geometry type (or none). This is causing a lot of the recent migration problems (geometry type invalid).

To do:
- Fix this. I suspect the problem is here: https://github.com/CartoDB/dataservices-api/blob/development/client/sql/21_bulk_geocoding_functions.sql#L61
- Fix it for existing users. I'd suggest tweaking and running the following rake: https://github.com/CartoDB/cartodb/blob/master/lib/tasks/db_maintenance.rake#L1388-L1405. Tip from @ramiroaznar: Table prefix `analysis_1ea6dec9f3_` means street address georeference analysis (the first of the analysis name is a hash of the type of analysis)
- Bonus: investigate how come postgres does not complain of this problem while running the analysis.

cc @CartoDB/rt-managers

**Comment by ethervoid** [comment]
I've found this bug in migrations but I thought it was a past bug solved that remains in some clients :thinking:

**Comment by javitonino** [comment]
Nope. It's very similar to an old bug for the isolines analysis.

Old bug: https://github.com/CartoDB/cartodb-central/issues/2151
And the fix: https://github.com/CartoDB/dataservices-api/pull/488

However, this is for the street geocoder and it's happening in fresh accounts.

**Comment by ethervoid** [comment]
Yep, I see. It's a weird one because the analysis shouldn't work trying to put Points into Polygons.

**Comment by javitonino** [comment]
This has been deployed and is currently running the rake for older users, which will take a while. Closing this anyway, since it will finish soon.
