### ISSUE TITLE
Add cdb_bulk_geocode_street_point function into Developer Center

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/dataservices-api#550]
In the Developer Center we're only documenting the street geocoding function [cdb_geocode_street_point](https://carto.com/developers/data-services-api/reference/#geocoding-functions) which is returning the geocodified coordinates from street addresses.

However, there is the [cdb_bulk_geocode_street_point](https://github.com/CartoDB/dataservices-api/blob/master/client/sql/21_bulk_geocoding_functions.sql) function that is being used in the [street geocoding analysis in Builder](https://github.com/CartoDB/camshaft/blob/master/lib/node/nodes/georeference-street-address.js#L94) that is not being documented.

@CartoDB/dc-managers 
cc @jsanz

**Comment by danicarrion** [comment]
related/duplicate: https://github.com/CartoDB/dataservices-api/issues/531

**Comment by oriolbx** [comment]
ok, closing then. Thanks @danicarrion ! :)
