### ISSUE TITLE
Broken integration tests 

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/dataservices-api#560]
Running the integration tests against either staging or production fails:

```
Ran 89 tests in 72.107s

FAILED (errors=1, failures=4)
```

We need to fix them and have a standarized way to run them (user with the proper rights, api key, etc).

**Comment by manmorjim** [comment]
With #592 the integration tests have been adapted and included in the CI but a random timeout error is still occurring in jenkins. We have to check it and fix it in order to close this.

**Comment by Algunenano** [comment]
Closing as done as they are now integrated into the PR system
