### ISSUE TITLE
Upgrade to Python3 for PG12/PGIS3

### ISSUE THREAD

**Issue by sabman** [CartoDB/dataservices-api#579]
I'm trying to get dataservices working with PG12 install. Currently tests and installation fails due to explicit dependence on `plpython2`/`python2.x`. I am going to start porting this to `plpython3` and `python3`. To avoid doubling up on work can someone inform me if this is already underway? There's a reference to this issue in https://github.com/CartoDB/dataservices-api/pull/578#issuecomment-585171546 If not, I'll create a fork and try to update.

**Comment by Algunenano** [comment]
Hi @sabman, we are planning on updating the extension to use plpython3 and Postgis 3.0 with PG12  but it's not in progress yet. The CI (is in place)[https://github.com/CartoDB/dataservices-api/runs/440823257] but we haven't started working on it yet.

**Comment by manmorjim** [comment]
With #592 dataservices should work with PG12 and Postgis3:
- It uses plpython3 or plpython depending on the PostgreSQL version.
- It creates the raster types needed if the postgis3 raster extension is not installed (this extension is optional).

**Comment by sabman** [comment]
😍🥳
-- 
http://twitter.com/sabman
